Repository boostcamp-2020/IssueTracker-26, pull requests merged in 2020-11, with the labels that each got.

#47 #10 - 레이블 목록 보기 API
  src/server/controllers/labelController.js
  src/server/models/labelModel.js
  src/server/models/queries.js
  src/server/routes/labelRouter.js
  src/server/services/labelService.js
  src/server/tests/label.test.js
Labels: backend, feat

#48 #18 - 이슈 등록하기 API 구현
  src/server/controllers/issueController.js
  src/server/models/issueModel.js
  src/server/models/queries.js
  src/server/routes/issueRouter.js
  src/server/services/issueService.js
  src/server/tests/issue.test.js
Labels: backend, feat

#50 #25 - 이슈 활성화 API 구현
  src/server/controllers/issueController.js
  src/server/models/issueModel.js
  src/server/models/queries.js
  src/server/routes/issueRouter.js
  src/server/services/issueService.js
  src/server/tests/issue.test.js
Labels: backend, feat

#51 #21 - 마일스톤 수정 api
  src/server/controllers/milestoneController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/routes/milestoneRouter.js
  src/server/services/milestoneService.js
  src/server/tests/milestone.test.js
Labels: backend, feat

#52 #34 - 회원가입, 로그인에 비밀번호 암호화 적용
  src/server/config/passportConfig.js
  src/server/package-lock.json
  src/server/package.json
  src/server/services/userService.js
  src/server/tests/user.test.js
  src/server/util/index.js
Labels: backend, feat

#54 #15 - comment 삭제 API
  src/server/controllers/commentController.js
  src/server/models/commentModel.js
  src/server/models/queries.js
  src/server/routes/commentRouter.js
  src/server/services/commentService.js
  src/server/tests/comment.test.js
Labels: backend, feat

#56 #12 - comment 수정 API
  src/server/controllers/commentController.js
  src/server/models/commentModel.js
  src/server/models/mentionModel.js
  src/server/models/queries.js
  src/server/routes/commentRouter.js
  src/server/services/commentService.js
  src/server/tests/comment.test.js
Labels: backend, feat

#55 #16 - 레이블 수정 API
  src/server/controllers/labelController.js
  src/server/models/labelModel.js
  src/server/models/queries.js
  src/server/routes/labelRouter.js
  src/server/services/labelService.js
  src/server/tests/label.test.js
Labels: backend, feat

#59 #20 - 레이블 삭제 API
  src/server/controllers/labelController.js
  src/server/models/labelModel.js
  src/server/models/queries.js
  src/server/routes/labelRouter.js
  src/server/services/labelService.js
  src/server/tests/label.test.js
Labels: backend, feat

#57 #27 - 마일스톤 목록 보기 API
  src/server/.eslintrc.js
  src/server/controllers/milestoneController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/routes/milestoneRouter.js
  src/server/services/milestoneService.js
  src/server/tests/milestone.test.js
Labels: backend, feat

#58 #9 - 마일스톤 삭제 API
  src/server/controllers/milestoneController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/routes/milestoneRouter.js
  src/server/services/milestoneService.js
  src/server/tests/milestone.test.js
Labels: backend, feat

#60 #22 - 이슈 수정하기 API 구현
  src/server/controllers/issueController.js
  src/server/models/issueModel.js
  src/server/models/queries.js
  src/server/routes/issueRouter.js
  src/server/services/issueService.js
  src/server/tests/issue.test.js
Labels: backend, feat

#77 #62 -드랍 메뉴 스타일 컴포넌트 구현
  src/client/src/components/DropBox.js
  src/client/src/components/Theme.js
Labels: feat, front

#79 #버튼 - 버튼 UI 컴포넌트 구현(레이블, 마일스톤, 이슈 등)
  src/client/src/components/Button.js
  src/client/src/components/Theme.js
Labels: feat, front

#78 #63 - input 컴포넌트 구현
  src/client/src/components/input/InputComponent.js
Labels: feat, front

#81 #61 - 로그인 컴포넌트 (UI만)
  src/client/src/components/Theme.js
  src/client/src/components/input/InputComponent.js
  src/client/src/components/login/LoginComponent.js
  src/client/src/pages/LoginPage.js
Labels: feat, front

#80 #64 - textarea 컴포넌트
  src/client/src/components/Textarea.js
Labels: feat, front

#82 #67 - Label/Milestone버튼 컴포넌트 생성
  src/client/src/components/LabelMilestoneButton.js
  src/client/src/components/app.js
  src/client/src/pages/LabelPage.js
  src/client/src/pages/MilestonePage.js
Labels: feat, front

#85 #75, #66 - 메인 페이지 구현
  src/client/package-lock.json
  src/client/package.json
  src/client/public/images/calendar.svg
  src/client/public/images/check.svg
  src/client/public/images/close-issue.svg
  src/client/public/images/comment.svg
  src/client/public/images/drop.png
  src/client/public/images/issue-milestone.svg
  src/client/public/images/normal-issue.svg
  src/client/public/images/open-issue.svg
  src/client/public/images/search-outline.svg
  src/client/public/images/setting.svg
  src/client/public/images/test.svg
  src/client/public/images/user.png
  src/client/src/components/App.js
  src/client/src/components/Button.js
  src/client/src/components/LabelMilestoneButton.js
  src/client/src/components/Theme.js
  src/client/src/components/header/Header.js
  src/client/src/components/input/InputComponent.js
  src/client/src/components/issueSection/IssueFilter.js
  src/client/src/components/issueSection/IssueHeader.js
  src/client/src/components/issueSection/IssueList.js
  src/client/src/components/issueSection/IssueSection.js
  src/client/src/pages/IssueCreatePage.js
  src/client/src/pages/MainPage.js
  src/client/src/util/time.js
  src/client/webpack.config.js
Labels: feat, front

#84 #61 - 로컬 로그인, 회원가입 client 구현
  src/client/src/components/App.js
  src/client/src/components/Button.js
  src/client/src/components/Context/UserContext.js
  src/client/src/components/GlobalStyle.js
  src/client/src/components/SharedStyle.js
  src/client/src/components/Textarea.js
  src/client/src/components/Theme.js
  src/client/src/components/input/InputComponent.js
  src/client/src/components/login/LoginComponent.js
  src/client/src/pages/LoginPage.js
  src/server/controllers/userController.js
Labels: feat, front

#88 #83- 이슈의 코멘트 개수 구하기(쿼리 수정)
  src/server/models/queries.js
Labels: backend, feat

#87 #83- 마일스톤 총 개수 구하기 API 구현
  src/server/controllers/milestoneController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/routes/milestoneRouter.js
  src/server/services/milestoneService.js
  src/server/tests/milestone.test.js
Labels: backend, feat

#86 #83- 레이블 총 개수 구하기 API 구현
  src/server/controllers/labelController.js
  src/server/models/labelModel.js
  src/server/models/queries.js
  src/server/routes/labelRouter.js
  src/server/services/labelService.js
  src/server/tests/label.test.js
Labels: backend, feat

#89 #75 - 이슈목록 불러오기 리팩토링 및 CSS 작업
  src/client/src/components/Theme.js
  src/client/src/components/header/Header.js
  src/client/src/components/input/InputComponent.js
  src/client/src/components/issueSection/IssueContent.js
  src/client/src/components/issueSection/IssueFilter.js
  src/client/src/components/issueSection/IssueHeader.js
  src/client/src/components/issueSection/IssueList.js
  src/client/src/components/issueSection/IssueListMenu.js
  src/client/src/components/login/LoginComponent.js
  src/server/controllers/userController.js
  src/server/routes/index.js
  src/server/routes/userRouter.js
  src/server/util/middleware.js
Labels: feat, front

#90 #83 - 라벨 및 마일스톤, 코멘트 총 개수 기능 구현
  src/client/src/components/input/InputComponent.js
  src/client/src/components/issueSection/IssueContent.js
  src/client/src/components/issueSection/IssueFilter.js
  src/client/src/components/issueSection/IssueHeader.js
Labels: feat, front

#91 #4 - auth, 로그인 로그아웃 구현
  src/client/src/components/App.js
  src/client/src/components/header/Header.js
  src/client/src/components/login/LoginComponent.js
  src/client/src/pages/MainPage.js
  src/server/config/passportConfig.js
  src/server/controllers/commentController.js
  src/server/routes/userRouter.js
Labels: feat, front

#93 #92 - 회원가입 시 비밀번호 확인 정상화
  src/client/src/components/SharedStyle.js
  src/client/src/components/input/InputComponent.js
  src/client/src/components/login/LoginComponent.js
Labels: bug, front

#94 #75 - 체크박스 선택으로 이슈 Open / Close 구현
  src/client/src/components/DropBox.js
  src/client/src/components/issueSection/IssueContent.js
  src/client/src/components/issueSection/IssueList.js
  src/client/src/components/issueSection/IssueListMenu.js
  src/client/src/components/issueSection/IssueSection.js
  src/client/src/util/http-common.js
  src/server/controllers/issueController.js
  src/server/services/issueService.js
Labels: feat, front

#96 #66 - 드롭 메뉴 필터의 드롭 박스 구현 및 업데이트
  src/client/src/components/DropBox.js
  src/client/src/components/issueSection/IssueListMenu.js
  src/client/src/components/listDropBox/Assignee.js
  src/client/src/components/listDropBox/Author.js
  src/client/src/components/listDropBox/Label.js
  src/client/src/components/listDropBox/Milstone.js
  src/server/controllers/milestoneController.js
  src/server/controllers/userController.js
  src/server/models/milestoneModel.js
  src/server/models/userModel.js
  src/server/routes/milestoneRouter.js
  src/server/routes/userRouter.js
  src/server/services/issueService.js
  src/server/services/milestoneService.js
  src/server/services/userService.js
Labels: backend, feat, front

#98 #69 - 레이블 목록, 생성 컴포넌트
  src/client/src/components/labelSection/LabelList.js
  src/client/src/components/labelSection/TouchLabel.js
  src/client/src/components/labelSection/index.js
  src/client/src/components/labelSection/labelStyle.js
  src/client/src/pages/LabelPage.js
Labels: feat, front

#99 #97 소셜 로그인 구현
  src/client/package-lock.json
  src/client/package.json
  src/client/src/components/App.js
  src/client/src/components/login/GitHubLogin.js
  src/client/src/components/login/LoginComponent.js
  src/server/config/passportConfig.js
  src/server/controllers/userController.js
  src/server/models/queries.js
  src/server/models/userModel.js
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/userRouter.js
  src/server/services/userService.js
Labels: backend, feat, front

#106 #70 - 마일스톤 목록 화면
  src/client/public/images/clear.svg
  src/client/src/components/LabelMilestoneButton.js
  src/client/src/components/milestoneSection/MilestoneHeader.js
  src/client/src/components/milestoneSection/MilestoneList.js
  src/client/src/components/milestoneSection/MilestoneListContent.js
  src/client/src/components/milestoneSection/MilestoneListMenu.js
  src/client/src/components/milestoneSection/MilestoneSection.js
  src/client/src/pages/MilestonePage.js
  src/server/models/queries.js
  src/server/services/milestoneService.js
Labels: backend, feat, front

#100 #68 - 레이블 수정 및 삭제
  src/client/src/components/labelSection/LabelList.js
  src/client/src/components/labelSection/TouchLabel.js
  src/client/src/components/labelSection/index.js
  src/client/src/components/labelSection/labelStyle.js
  src/server/issueTrackerDB.sql
Labels: feat, front

#104 #103 - 회원 가입 시 유저 중복 체크 구현, FlashMessage box 추가
  src/client/src/components/Button.js
  src/client/src/components/FlashMessage/Content.js
  src/client/src/components/FlashMessage/ProgressBar.js
  src/client/src/components/FlashMessage/index.js
  src/client/src/components/FlashMessage/keyframes.js
  src/client/src/components/input/InputComponent.js
  src/client/src/components/login/LoginComponent.js
  src/client/src/util/api/user.js
  src/client/src/util/index.js
Labels: feat, front

#105 #101, #102 - 로그아웃 시 state 초기화 수정, getUserInfo api 수정
  src/client/src/components/App.js
  src/client/src/components/header/Header.js
  src/server/controllers/userController.js
  src/server/models/queries.js
  src/server/models/userModel.js
  src/server/services/userService.js
Labels: bug, chore, front

#111 #110 - 이슈 등록하기 구현 완료!
  src/client/public/images/github.png
  src/client/src/components/Button.js
  src/client/src/components/DropBox.js
  src/client/src/components/Textarea.js
  src/client/src/components/issueForm/IssueForm.js
  src/client/src/components/issueForm/IssueSubMenu.js
  src/client/src/components/listDropBox/Assignee.js
  src/client/src/components/listDropBox/Label.js
  src/client/src/components/listDropBox/Milstone.js
  src/client/src/pages/IssueCreatePage.js
  src/server/controllers/milestoneController.js
  src/server/controllers/userController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/routes/milestoneRouter.js
  src/server/services/issueService.js
  src/server/services/milestoneService.js
Labels: backend, feat, front

#108 #107 - 레이블 글자색 자동 변경, 기존 스타일 수정
  src/client/public/images/changeLabel.svg
  src/client/src/components/labelSection/LabelList.js
  src/client/src/components/labelSection/TouchLabel.js
  src/client/src/components/labelSection/index.js
  src/client/src/components/labelSection/labelStyle.js
  src/client/src/components/labelSection/utils.js
  src/client/src/pages/LabelPage.js
Labels: feat, front

#109 #70 - 마일스톤 목록 구현
  src/client/src/components/header/Header.js
  src/client/src/components/issueSection/IssueContent.js
  src/client/src/components/milestoneSection/MilestoneList.js
  src/client/src/components/milestoneSection/MilestoneListContent.js
  src/client/src/components/milestoneSection/MilestoneListMenu.js
  src/client/src/util/time.js
Labels: feat, front, refactor

#114 #115 - 이슈 디테일 페이지 구현
  src/client/src/components/App.js
  src/client/src/components/Context/IssueDetailContext.js
  src/client/src/components/GlobalStyle.js
  src/client/src/components/IssueDetail/IssueDetailContainer.js
  src/client/src/components/IssueDetail/IssueDetailPresenter.js
  src/client/src/components/IssueDetail/IssuePost.js
  src/client/src/components/IssueDetail/IssuePostForm.js
  src/client/src/components/IssueDetail/IssueSideMenu.js
  src/client/src/components/IssueDetail/ListDropBox/Assignee.js
  src/client/src/components/IssueDetail/ListDropBox/DropBox.js
  src/client/src/components/IssueDetail/ListDropBox/Label.js
  src/client/src/components/IssueDetail/ListDropBox/Milstone.js
  src/client/src/components/IssueDetail/action.js
  src/client/src/components/IssueDetail/index.js
  src/client/src/components/IssueDetail/reducer.js
  src/client/src/components/issueSection/IssueContent.js
  src/client/src/components/shared/sharedComponents.js
  src/client/src/pages/IssueDetailPage.js
  src/client/src/util/api/issue.js
  src/server/models/queries.js
Labels: feat, front

#118 #70, #26 - 마일스톤 목록 페이지 완료
  src/client/src/components/App.js
  src/client/src/components/LabelMilestoneButton.js
  src/client/src/components/input/InputComponent.js
  src/client/src/components/issueSection/IssueContent.js
  src/client/src/components/labelSection/labelStyle.js
  src/client/src/components/milestoneSection/MilestoneCreateSection.js
  src/client/src/components/milestoneSection/MilestoneHeader.js
  src/client/src/components/milestoneSection/MilestoneList.js
  src/client/src/components/milestoneSection/MilestoneListContent.js
  src/client/src/pages/MilestoneCreatePage.js
  src/client/src/pages/MilestoneEditPage.js
  src/server/controllers/milestoneController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/routes/milestoneRouter.js
  src/server/services/milestoneService.js
Labels: backend, feat, front, refactor

#119 #74 - 드롭박스 필터 기능 구현
  src/client/package-lock.json
  src/client/package.json
  src/client/public/images/clear.png
  src/client/public/images/clearHover.png
  src/client/src/components/issueForm/IssueSubMenu.js
  src/client/src/components/issueSection/IssueContent.js
  src/client/src/components/issueSection/IssueFilter.js
  src/client/src/components/issueSection/IssueHeader.js
  src/client/src/components/issueSection/IssueList.js
  src/client/src/components/issueSection/IssueListMenu.js
  src/client/src/components/issueSection/IssueSection.js
  src/client/src/components/listDropBox/Assignee.js
  src/client/src/components/listDropBox/Author.js
  src/client/src/components/listDropBox/Label.js
  src/client/src/components/listDropBox/Milstone.js
  src/client/src/pages/IssueCreatePage.js
  src/client/src/util/filter.js
  src/server/controllers/issueController.js
  src/server/models/issueModel.js
  src/server/models/queries.js
  src/server/routes/issueRouter.js
  src/server/services/issueService.js
Labels: feat, front

#120 #115 - 이슈 디테일
  src/client/src/components/App.js
  src/client/src/components/IssueDetail/IssueDetailContainer.js
  src/client/src/components/IssueDetail/IssueDetailPresenter.js
  src/client/src/components/IssueDetail/IssuePost.js
  src/client/src/components/IssueDetail/IssueSideMenu.js
  src/client/src/components/IssueDetail/action.js
  src/client/src/components/IssueDetail/reducer.js
  src/client/src/components/commentSection/Style.js
  src/client/src/components/commentSection/TouchComment.js
  src/client/src/components/commentSection/index.js
  src/client/src/util/api/comment.js
  src/client/src/util/api/issue.js
  src/server/controllers/commentController.js
  src/server/models/commentModel.js
  src/server/models/queries.js
  src/server/services/commentService.js
Labels: feat, front

#123 #112 - 필터 헤더부분 CSS 수정
  src/client/src/components/issueSection/IssueHeader.js
  src/client/src/components/issueSection/IssueSection.js
Labels: bug, front

#121 #116 - 코멘트 생성시 이미지 업로드 기능 추가
  src/client/env
  src/client/package-lock.json
  src/client/package.json
  src/client/src/components/IssueDetail/IssuePost.js
  src/client/src/components/Textarea.js
  src/client/src/components/commentSection/Style.js
  src/client/src/components/commentSection/TouchComment.js
  src/client/src/components/imageUpload/ImageUpload.js
  src/client/src/components/imageUpload/index.js
  src/client/webpack.config.js
Labels: feat, front

#122 #71, #72 - 마일스톤 생성하기 페이지 및 폼 컴포넌트 분리
  src/client/src/components/milestoneSection/MilestoneCreateSection.js
  src/client/src/components/milestoneSection/MilestoneForm.js
Labels: feat, front, refactor

#125 #116 - 이슈 생성/수정, 코멘트 수정 시 이미지 업로드 구현
  src/client/.eslintrc.js
  src/client/src/components/IssueDetail/IssuePostForm.js
  src/client/src/components/Textarea.js
  src/client/src/components/commentSection/TouchComment.js
  src/client/src/components/issueForm/IssueForm.js
  src/client/src/pages/IssueCreatePage.js
  src/client/src/util/handleFile.js
  src/client/src/util/tag-generator.js
Labels: enhancement, feat, front, refactor

#127 #73 - 마일스톤 수정하는 페이지 기능 구현
  src/client/src/components/App.js
  src/client/src/components/milestoneSection/MilestoneEditSection.js
  src/client/src/components/milestoneSection/MilestoneListContent.js
  src/client/src/pages/MilestoneEditPage.js
  src/server/controllers/milestoneController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/routes/milestoneRouter.js
  src/server/services/milestoneService.js
Labels: backend, bug, feat, front

#128 #112 - Footer 추가 및 Hearder 색상 수정
  src/client/src/components/App.js
  src/client/src/components/Footer.js
  src/client/src/components/header/Header.js
  src/client/src/components/issueForm/IssueForm.js
  src/client/src/components/issueSection/IssueContent.js
  src/server/models/queries.js
Labels: front

#126 #112 - issue 디테일 style 수정
  src/client/src/components/IssueDetail/IssueDetailPresenter.js
  src/client/src/components/IssueDetail/IssuePost.js
  src/client/src/components/commentSection/Style.js
  src/client/src/components/commentSection/TouchComment.js
Labels: front

#130 Fix:마일스톤 버그 수정
  src/client/src/components/milestoneSection/MilestoneCreateSection.js
  src/client/src/components/milestoneSection/MilestoneEditSection.js
  src/client/src/components/milestoneSection/MilestoneForm.js
  src/client/src/components/milestoneSection/MilestoneListContent.js
  src/client/src/util/time.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
Labels: bug, refactor

#131 #113 - milestone create, edit 수정
  src/server/controllers/milestoneController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/services/milestoneService.js
Labels: backend, bug

#132 #113 - 이슈 상태 변경 시 마일스톤 ratio 업데이트 & 깃헙 로그인 시 state 변경 시 오류 수정
  src/client/src/components/IssueDetail/IssueDetailContainer.js
  src/client/src/components/IssueDetail/IssueDetailPresenter.js
  src/client/src/components/IssueDetail/IssueSideMenu.js
  src/client/src/components/IssueDetail/action.js
  src/client/src/components/IssueDetail/reducer.js
  src/client/src/components/login/GitHubLogin.js
  src/client/src/util/api/milestone.js
  src/server/controllers/userController.js
  src/server/models/queries.js
Labels: backend, bug, chore, feat, front

#133 #113 - 마일스톤 및 필터 버그수정
  src/client/src/components/milestoneSection/MilestoneEditSection.js
  src/client/src/components/milestoneSection/MilestoneForm.js
  src/server/models/queries.js
Labels: bug

#134 마일스톤 삭제
  src/client/src/components/milestoneSection/MilestoneEditSection.js
  src/client/src/components/milestoneSection/MilestoneListContent.js
Labels: feat, front, refactor

#135 #113 - issue post form 프로필 수정
  src/client/src/components/IssueDetail/IssuePost.js
  src/client/src/components/IssueDetail/IssuePostForm.js
Labels: bug, front

#136 #113 - 라벨 드롭박스 CSS 수정
  src/client/src/components/listDropBox/Label.js
Labels: bug, front
