Repository boostcamp-2020/IssueTracker-26, pull requests merged in 2020-10, with the labels that each got.

#28 #2 - 개발 환경 설정
  .gitignore
  README.md
  src/client/.babelrc
  src/client/.eslintrc.js
  src/client/.prettierrc
  src/client/package-lock.json
  src/client/package.json
  src/client/src/components/app.js
  src/client/src/index.html
  src/client/src/index.js
  src/client/webpack.config.js
  src/server/.eslintrc.js
  src/server/.prettierrc
  src/server/app.js
  src/server/bin/www
  src/server/config/db-config.js
  src/server/controllers/index.js
  src/server/env
  src/server/issueTrackerDB.sql
  src/server/models/index.js
  src/server/package-lock.json
  src/server/package.json
  src/server/public/index.js
  src/server/routes/index.js
  src/server/services/index.js
Labels: chore

#29 #5 - DB 설계 및 ERD 작성
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/client/src/util/index.js
  src/server/config/db-config.js
  src/server/env
  src/server/util/index.js
Labels: chore

#31 #1 - 회원가입 API 구현
  src/server/controllers/commentController.js
  src/server/controllers/issueController.js
  src/server/controllers/labelController.js
  src/server/controllers/milestoneController.js
  src/server/controllers/userController.js
  src/server/models/assigneeModel.js
  src/server/models/commentModel.js
  src/server/models/issueModel.js
  src/server/models/labelModel.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/models/userModel.js
  src/server/routes/commentRouter.js
  src/server/routes/index.js
  src/server/routes/issueRouter.js
  src/server/routes/labelRouter.js
  src/server/routes/milestoneRouter.js
  src/server/routes/userRouter.js
  src/server/services/assigneeService.js
  src/server/services/commentService.js
  src/server/services/issueService.js
  src/server/services/labelService.js
  src/server/services/milestoneService.js
  src/server/services/userService.js
  src/server/tests/index.js
  src/server/tests/user.test.js
Labels: backend, feat

#35 #33 - userName 중복체크 API
  src/server/controllers/userController.js
  src/server/models/userModel.js
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/userRouter.js
  src/server/services/userService.js
  src/server/tests/checkDuplicated.test.js
  src/server/tests/user.test.js
Labels: backend, feat

#36 #6 - 마일스톤 생성 API 구현
  src/server/controllers/milestoneController.js
  src/server/models/milestoneModel.js
  src/server/models/queries.js
  src/server/routes/index.js
  src/server/routes/milestoneRouter.js
  src/server/services/milestoneService.js
  src/server/tests/milestone.test.js
Labels: backend, feat

#40 #39 - 마일스톤 생성 시 기본값 오류
  README.md
  src/server/controllers/milestoneController.js
Labels: backend, bug

#45 #3 - GitHub Oauth 적용
  src/server/app.js
  src/server/config/passportConfig.js
  src/server/controllers/userController.js
  src/server/env
  src/server/models/queries.js
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/userRouter.js
  src/server/tests/user.test.js
  src/server/util/index.js
Labels: backend, feat
